runtime: nodejs
env: flex
manual_scaling:
 instances: 1 
env_variables:
 MYSQL_USER: root
 MYSQL_PASSWORD: '12345678'
 MYSQL_DATABASE: caravan 
 INSTANCE_CONNECTION_NAME: caravan2020:us-central1:caravan
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console. 
 cloud_sql_instances: caravan2020:us-central1:caravan 
skip_files: 
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^(.*/)?.*\.ts$
 - ^(.*/)?config\.development\.json$
